"""make_historial_usuario_id_nullable

Revision ID: cc122d35b334
Revises: a1b2c3d4e5f6
Create Date: 2026-06-07 23:15:12.809309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc122d35b334'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pago',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.BigInteger(), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='pendiente', nullable=False),
    sa.Column('mp_preference_id', sa.String(length=255), nullable=True),
    sa.Column('mp_init_point', sa.String(length=500), nullable=True),
    sa.Column('mp_payment_id', sa.BigInteger(), nullable=True),
    sa.Column('mp_merchant_order_id', sa.BigInteger(), nullable=True),
    sa.Column('mp_status', sa.String(length=30), nullable=True),
    sa.Column('mp_status_detail', sa.String(length=100), nullable=True),
    sa.Column('external_reference', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('transaction_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_reference', name='uq_pago_external_reference'),
    sa.UniqueConstraint('idempotency_key', name='uq_pago_idempotency_key'),
    sa.UniqueConstraint('mp_payment_id', name='uq_pago_mp_payment_id')
    )
    op.alter_column('historial_estado_pedido', 'usuario_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('historial_estado_pedido', 'usuario_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_table('pago')
    # ### end Alembic commands ###
